# Generated by Django 5.1.5 on 2025-03-07 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fairaddress',
            options={'verbose_name': 'Endereço da Feira', 'verbose_name_plural': 'Endereços da Feira'},
        ),
        migrations.RemoveField(
            model_name='fair',
            name='days',
        ),
        migrations.CreateModel(
            name='FairDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira'), ('sab', 'Sábado'), ('dom', 'Domingo')], max_length=3)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_days', to='location.fair')),
            ],
        ),
    ]
