# Generated by Django 5.1.5 on 2025-03-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_fair_address_alter_fairday_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairaddress',
            name='latitude',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='fairaddress',
            name='longitude',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Longitude'),
        ),
    ]
