# Generated by Django 5.1.5 on 2025-03-08 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_fair_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fair',
            options={'verbose_name': 'Feira', 'verbose_name_plural': 'Feiras'},
        ),
        migrations.AlterModelOptions(
            name='fairday',
            options={'verbose_name': 'Dia da Feira', 'verbose_name_plural': 'Dias das Feiras'},
        ),
        migrations.RemoveField(
            model_name='fair',
            name='user',
        ),
        # migrations.AlterUniqueTogether(
        #     name='fairday',
        #     unique_together={('address', 'day')},
        # ),
        migrations.AddField(
            model_name='fair',
            name='users',
            field=models.ManyToManyField(related_name='fairs', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.AddField(
        #     model_name='fairday',
        #     name='address',
        #     field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fair_days', to='location.fairaddress'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='fair',
        #     name='address',
        #     field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fairs', to='location.fairaddress'),
        # ),
        migrations.RemoveField(
            model_name='fairday',
            name='fair',
        ),
    ]
