# Generated by Django 5.1.5 on 2025-03-08 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_fair_options_alter_fairday_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fairday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fairday',
            name='fair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fair_days', to='location.fair'),
        ),
        # migrations.RemoveField(
        #     model_name='fairday',
        #     name='address',
        # ),
    ]
