# Generated by Django 5.1.5 on 2025-01-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'permissions': [('view_vendor_dashboard', 'Can view vendor dashboard'), ('edit_vendor_profile', 'Can edit vendor profile')], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
