# Generated by Django 5.1.5 on 2025-02-03 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Endereço padrão'),
        ),
    ]
